apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: \$(NSP-IP)
    path: /srv/nfs/kubedata
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gooseprawn-app
spec:
  selector:
    matchLabels:
      app: goose-prawn
  template:
    metadata:
      labels:
        app: goose-prawn
    spec:
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-pvc
      containers:
      - name: web-container
        image: nginx
        volumeMounts:
        - mountPath: /tmp/data_
          name: nfs-storage
        - mountPath: /tmp/data
          name: nfs-storage
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "200m"
          requests:
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  type: NodePort
  selector:
    app: goose-prawn
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 8080   
      nodePort: 30001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: goose-hpa
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gooseprawn-app
  targetCPUUtilizationPercentage: 67