apiVersion: v1
kind: PersistentVolumeClaim  #in dynamic pv (allowvloume expnsion)
metadata:                    #storageclass/nfs provisioner and RBAC
  name: nfs-pvc              #are required for role/clusterRole permission
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nfs-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi

apiVersion: v1
kind: PersistentVolumeClaim  
metadata:                    
  name: nfs-pvc              
spec:
  storageClassName: nfs-strg-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi